awk in place

diff --git a/scripts/main b/scripts/main
--- a/scripts/main
+++ b/scripts/main
@@ -9,6 +9,12 @@ then
   exit 1
 fi
 
+if [ ! -x $NODEPATH/node ] 
+then
+  echo "$0 error: node command not found"
+  exit 1
+fi
+
 $NODEPATH/node $MYPATH/index.js $@
 
 declare -a prefixes 
